/*
	@file	Sounds.h
	@brief	‰¹Œ¹
*/
#pragma once

enum XACT_WAVEBANK_SOUNDS : unsigned int
{
	XACT_WAVEBANK_SOUNDS_TITLESCENE_BGM			= 0,
	XACT_WAVEBANK_SOUNDS_SELECTSCENE_BGM		= 1,
	XACT_WAVEBANK_SOUNDS_PLAYSCENE_BGM			= 2,
	XACT_WAVEBANK_SOUNDS_RESULTSCENEWIN_BGM		= 3,
	XACT_WAVEBANK_SOUNDS_RESULTSCENELOSE_BGM	= 4,
	XACT_WAVEBANK_SOUNDS_CANNONBALL_SE			= 5,
	XACT_WAVEBANK_SOUNDS_BULLET_SE				= 6,
	XACT_WAVEBANK_SOUNDS_RELOAD_SE				= 7,
	XACT_WAVEBANK_SOUNDS_NONEBULLETS_SE			= 8,
	XACT_WAVEBANK_SOUNDS_DAMAGE_SE				= 9,
	XACT_WAVEBANK_SOUNDS_BREAK_SE				= 10,
	XACT_WAVEBANK_SOUNDS_BUTTON_SE				= 11,
	XACT_WAVEBANK_SOUNDS_CURSOR_SE				= 12
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT 13